### ISSUE TITLE
When adding a URL reference, add today's date per default

### ISSUE THREAD

**Issue by vrandezo** [google/primarysources#1]
When adding a URL reference (i.e. per P854) add per default also P813 with the day of that edit (i.e. stating when this was retrieved.

**Comment by lydiapintscher** [comment]
:+1:

**Comment by tomayac** [comment]
This blindly assumes that the URL was actually retrieved and checked by the user. Is this intended? Or should I enforce a check if the URL was indeed opened?

**Comment by tomayac** [comment]
Cleaning up the issues list, let's track this under https://github.com/google/primarysources/issues/5, please add future comments there. Thanks!
