### ISSUE TITLE
TypeError: objectLabels is undefined on suggested claims to non-item entities

### ISSUE THREAD

**Issue by mineo** [google/primarysources#10]
On https://www.wikidata.org/wiki/Q2552978 the above error occurs (at least in Firefox 36 and GNOMEs Epiphany browser) on https://github.com/google/primarysources/blob/0eb307c2cbf4b40ba14f188526b624809c977b5b/frontend/freebase2wikidata.js#L762

I think this is because assumes that the suggested item on the other end of the new claim is an item in Wikidata but in this case it's just the MusicBrainz artist identifier. The call to https://www.wikidata.org/w/api.php?action=wbgetentities&languages=en&format=json&props=labels&ids=%221b2cd3ab-a722-4786-a99e-aef61089dd35%22 then returns only an error message in the body but the status code is still 200.

**Comment by tomayac** [comment]
Thanks, this has been fixed with https://github.com/google/primarysources/commit/c0cd80c052036c1be3c31093ea6ce6f695a51b65.
