### ISSUE TITLE
"Approve claim" adds the claim with no reference

### ISSUE THREAD

**Issue by marfox** [google/primarysources#103]
For instance, in https://www.wikidata.org/wiki/Q21536207#revision=333165966 :

- if you first approve the (referenced) **claim**, it is added with no reference (cf. top one);
- if you then approve the **reference**, it is duplicated in a **new** claim (cf. 2nd one);
- the whole claim is still suggested (cf. bottom one, see #94)

I think this is a major source of frustration for users of the tool.

**Comment by tomayac** [comment]
Closing, and leaving https://github.com/google/primarysources/issues/94 open instead.
