### ISSUE TITLE
Invalid snak when accepting a claim

### ISSUE THREAD

**Issue by marfox** [google/primarysources#107]
Reported by a user in https://www.wikidata.org/wiki/Q21454708
Maybe related to [this](83#issuecomment-201227191) in #83 .

The loader animation does not stop neither, maybe related to #44 .

**Comment by tomayac** [comment]
I can't reproduce this on the item in question. Have a different example?

**Comment by marfox** [comment]
https://www.wikidata.org/wiki/Q3568877
It seems to happen for `strephit` statements only.

**Comment by tomayac** [comment]
Strange. I just disapproved the statement [without issue](https://tools.wmflabs.org/wikidata-primary-sources/entities/Q3568877?dataset=).

**Comment by marfox** [comment]
Yes, `freebase` seems to be working fine indeed.
I looked up the Item again, and the `birth name` statement suggested by `strephit` is no longer there.
Very strange.
Could you please try with https://www.wikidata.org/wiki/Q429607 , statement `country of citizenship`?

**Comment by tomayac** [comment]
I switched to ```strephit``` and [approved references and claims](https://www.wikidata.org/w/index.php?title=Q442491&action=history&year=2016&month=-1&tagfilter=) successfully. While I did hit the occasional approved claims reappearing issue from https://github.com/google/primarysources/issues/94, all else succeeded. If you hit this the next time, can you try to remember the data type, please?

**Comment by marfox** [comment]
You are right, @tomayac, it works fine with **Time** data types, cf. [this edit](https://www.wikidata.org/w/index.php?title=Q5592&action=history), and **Item** ones, cf. [this edit](https://www.wikidata.org/w/index.php?title=Q643494&action=history).

I can reproduce the issue with **Monolingual text** data types, cf. `birth name` statement in [this Item](https://www.wikidata.org/wiki/Q92332).
I guess this is due to a problem in the QuickStatements serialization of the dataset: the [service](http://tools.wmflabs.org/wikidata-todo/quick_statements.php) that includes the syntax documentation is currently not responding, I will investigate that.

Thanks for your precious support!

**Comment by marfox** [comment]
This is now working fine, cf. [this edit](https://www.wikidata.org/w/index.php?title=Q4718212&action=history)

The issue was in the dataset, not the tool, closing.
