### ISSUE TITLE
blacklist for references

### ISSUE THREAD

**Issue by lydiapintscher** [google/primarysources#11]
Some of the suggested reference URLs are probably not up to the community's standard because they are not considered reliable. Idea: provide the ability to blacklist domains that are generally not wanted as references.

**Comment by tomayac** [comment]
I'm happy to add this feature. Therefore, please start a blacklist (in a simple format like .tsv or .json) and let me know its URL, I'm happy to pull in the refreshed blacklist upon each session start.

**Comment by lydiapintscher** [comment]
Is wikitext ok too? Then I could start a page on-wiki so other people can help add URLs.

**Comment by tomayac** [comment]
As long as I can parse it somehow, all textual formats are fine :-)

**Comment by vrandezo** [comment]
I can also clean up the data before it even gets to the backend, if I have this list. Thank you that would be great.

**Comment by lydiapintscher** [comment]
Sweet. I started the page at https://www.wikidata.org/wiki/Wikidata:Primary_sources_tool/URL_blacklist

**Comment by wastl** [comment]
Again the question: should this be a frontend filter, or should we also mark blacklisted references in the backend database? If we don't mark it also in the backend, we will have a hard time keeping track of completed statements.

**Comment by tomayac** [comment]
IMHO definitely front-end. I can pull in the supposedly dynamic
blacklist upon each session start and just filter out dynamically.

**Comment by wastl** [comment]
When you are filtering, could you then also directly mark the filtered statements in the backend as "skipped"? This would solve both problems ;-)

I'll add support for skipped to the backend in an hour or so.

**Comment by tomayac** [comment]
> When you are filtering, could you then also directly mark the filtered statements in the backend as "skipped"?

I will do this. On a related note, shall we introduce "duplicate" as
an additional state, or should this be covered under the "skipped"
umbrella state?

**Comment by wastl** [comment]
I introduced now the additional states "duplicate" and "blacklisted". This change is not deployed yet, though, only in the code.

**Comment by wastl** [comment]
It's now live.

**Comment by tomayac** [comment]
This was closed with https://github.com/google/primarysources/commit/5dbbede66fa23f0c65416d2b1987eb3926bbe623.

**Comment by tomayac** [comment]
Corrected the state from "disapproved" to "blacklisted" in https://github.com/google/primarysources/commit/b70c2c42ec301350543d33e2bd26656c902f87f1.
