### ISSUE TITLE
suggestions does not show up

### ISSUE THREAD

**Issue by lydiapintscher** [google/primarysources#12]
I click the "Random Freebase item" link in the sidebar. Sometimes I end up on items with no suggestions. However one statement section looks different - like the suggestion wasn't properly expanded. Q381734 is one item where this happens.

![wikidataclientwatchlistintegration1](https://cloud.githubusercontent.com/assets/550412/6985380/fb58555e-da32-11e4-8b5f-7ed415e5a81b.png)

**Comment by tomayac** [comment]
This should have been fixed with https://github.com/google/primarysources/commit/932484bc5f769d47739c2ec34603edd3372dc23e. Please reopen if this is still an issue.
