### ISSUE TITLE
Approving one of multiple reference URLs for a new statement suggests the new unapproved ones under a new statement

### ISSUE THREAD

**Issue by mineo** [google/primarysources#16]
Check the attached screenshot. I approved the nataliezworld.com URL and after the automatic reload the remaining URL was suggested for a new statement, not the existing one.

![2](https://cloud.githubusercontent.com/assets/78236/7208213/6207046e-e53f-11e4-9d74-64fe26bcd73b.png)

**Comment by tomayac** [comment]
Thanks for reporting this. It is a known issue (https://github.com/google/primarysources/issues/15, albeit the connection may not seem obvious) that I am preparing to fix starting with https://github.com/google/primarysources/commit/53f9404cddf20e668c8252b2b88a0195b8f80190. Closing the current issue.

**Comment by tomayac** [comment]
This has now been fixed with https://github.com/google/primarysources/commit/f17130e7ce57efebf0de89b07f8e3d10b262d30b.
