### ISSUE TITLE
Got taken to an item without any suggested statements/references and no "Random Freebase item" link

### ISSUE THREAD

**Issue by mineo** [google/primarysources#17]
The latter is what makes me think this might not just be because of the duplicate check in the frontend in #8. The item in question is https://www.wikidata.org/wiki/Q328154 and the unapproved statements on it are currently (essentially some reference URLs for the country of citizenship claim):

```json
[
  {
    "format": "v1",
    "id": 348,
    "state": "unapproved",
    "statement": "Q328154\tP27\tQ38\tS854\t\"http:\/\/www.facebook.com\/pages\/Bar-Diana\/384325578246776\""
  },
  {
    "format": "v1",
    "id": 349,
    "state": "unapproved",
    "statement": "Q328154\tP27\tQ38\tS854\t\"http:\/\/trove.nla.gov.au\/work\/38044914\""
  },
  {
    "format": "v1",
    "id": 350,
    "state": "unapproved",
    "statement": "Q328154\tP27\tQ38\tS854\t\"http:\/\/journal.publications.chestnet.org\/article.aspx?articleid=1089909\""
  }
]```

This happens in Firefox 37.0.1 and Chromium 41.0.2272.118.

**Comment by tomayac** [comment]
Thanks for reporting this, however, the specific page
https://www.wikidata.org/wiki/Q328154 throws an error that is not in
the user script's code. It happens even before the user script gets
injected:
Uncaught Error: Not implemented yet. => VM206:132

**Comment by tomayac** [comment]
Maybe @LydiaPitscher kann escalate this to the Wikidata engineers.

**Comment by lydiapintscher** [comment]
I've fixed the item now. A bot made an error which broke it.
