### ISSUE TITLE
duplicate reference suggestions

### ISSUE THREAD

**Issue by JanZerebecki** [google/primarysources#18]
Suggestions are shown for references that already are there. Example:
https://www.wikidata.org/wiki/Q120419 has genre:Opera with reference url: http://pages.rediff.com/tsefal-i-prokris/1053996
Which is suggested again.

**Comment by tomayac** [comment]
Thanks for reporting this. I can reproduce the issue and am working on a fix, but can't commit to an ETA quite yet due to an ongoing conference trip and general backlog ;-) On my list, though.

**Comment by wastl** [comment]
Do you have a fix already? Otherwise we could have a cron job iterating over all entities and marking statements as duplicate that are already found in Wikidata.

**Comment by tomayac** [comment]
I guess this would be overkill, I can fix it ad-hoc in the front-end.
Haven't come to it yet (but will eventually); it's not a frequent
problem.
