### ISSUE TITLE
make testable on test.wikidata.org and beta

### ISSUE THREAD

**Issue by JanZerebecki** [google/primarysources#19]
Please make this testable on test.wikidata.org and wikidata.beta.wmflabs.org .

To support this use absolute URLs in the frontend JS for loading scripts and css. And replace importStylesheet with the mw.loader.load variant, because it doesn't support absolute URLs.

Then it can be loaded from e.g. test.wikidata.org without needing to duplicate the code on local wiki pages.

If the tool has specific known property IDs then those need to be different for test and beta.

**Comment by JanZerebecki** [comment]
The first two lines that were relative I have seen:
var asyncSrc = '/w/index.php?title=User:Tomayac/async.js&action=raw' +'&ctype=text%2Fjavascript';
importStylesheet('User:Tomayac/freebase2wikidata.css');

**Comment by JanZerebecki** [comment]
This ticket was reported while https://phabricator.wikimedia.org/T95289#1265861 .

**Comment by tomayac** [comment]
Thanks for the issue report, closed it with https://github.com/google/primarysources/commit/cc2da3c08b7663a24343d7dd94b34410e7d84d68, all URLs of external sources are absolute now.
