### ISSUE TITLE
After I enriched a reference, it is suggested again

### ISSUE THREAD

**Issue by vrandezo** [google/primarysources#2]
I chose a good reference, but added "retrieved (P813): April 1, 2015" to it. When I reload the page, the same reference is suggested again.

I tried it here: https://www.wikidata.org/wiki/Q357106 (see history)

**Comment by vrandezo** [comment]
Ah, this seems not to happen when I "accept" it and then "edit" it, but when I "edit" and then "save" it.

**Comment by tomayac** [comment]
I believe this is working as intended. First, you have to accept, then you can add additional metadata. Please reopen if you disagree.
