### ISSUE TITLE
Implement the distinction between string and monolingualtext

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#21]
There is in Wikidata a specific datatype for strings with language that is "monolingualtext" The "string" datatype is only for language independent strings (like identifiers).

The JSON serialization should maybe be changed to reflect this distinction.

**Comment by tomayac** [comment]
I need to look closer into this. If I recall correctly, the code currently falls back to "string" as the default type. By "JSON serialization", whose serialization do you mean? Wikidata's or the Primary Sources tool's?

**Comment by wastl** [comment]
Do you have a concrete example of where this is wrong? At least in the primary sources tool backend the implementation should be correct. It has two serializations:
- TSV is the compact tab separated format, literals with language specification look like en:"Hello World", and without language specification like "1234".
- Wikidata JSON is the complex snak format used by wikidata; here, a string litera has type: "string", and if it has a language specifier also language: "blah".
In the frontend, we are using the TSV format, so the Wikidata JSON format returned by the backend should not make any difference, even if it is wrong.

**Comment by Tpt** [comment]
I mean the Wikidata JSON.

> here, a string literal has type: "string", and if it has a language specifier also language: "blah".

No, there are two datatypes:

"string" for language independence strings:

```
{
    value: "foo",
    type: "string"
}
```

"monolingualtext" for strings with a language:

```
{
    value: {
        text: "Obituary: Douglas Adams",
        language: "en"
    },
    type: "monolingualtext"
}
```

Example: https://www.wikidata.org/wiki/Special:EntityData/Q42.json


As the Wikidata JSON seems to be unused feel free to close this bug.
