### ISSUE TITLE
Rejecting a property with multiple sources rejects only one of the sources

### ISSUE THREAD

**Issue by mineo** [google/primarysources#25]
https://www.wikidata.org/wiki/Q717642 suggested the place of birth to be Latvia with 3 sources, but there's already a more specific POB, so I rejected the new property/statement. Unfortunately that only rejected one of the sources, reloaded the page and suggested the whole thing again with one less source. Ideally all of the sources and the property itself would be rejected at once.

**Comment by mineo** [comment]
https://www.wikidata.org/wiki/Q1445666 is an item with basically the same situation, but where I did not yet reject everything, so you can use it for testing.

**Comment by JeanFred** [comment]
Confirming the described behaviour.

**Comment by jeblad** [comment]
There is a bug report in Phabricator; [[https://phabricator.wikimedia.org/T104815 | Reject of entries in the Primary sources tool fails ]]. It could be the same bug, but in this case removal of the last source fails.

**Comment by mbch331** [comment]
This is still an issue and it's rather irritating that I have to reject a claim x times, because there are x references.
