### ISSUE TITLE
Implement Frontend (Javascript) Tests

### ISSUE THREAD

**Issue by wastl** [google/primarysources#33]
As we now have Travis integration, it would be useful to structure the frontend code into components and have them unit tested similar to the backend.

**Comment by tomayac** [comment]
Non-trivial time-wise, technically [all possible](https://docs.travis-ci.com/user/gui-and-headless-browsers/) and faciliated through Wikidata [sandbox items](https://www.wikidata.org/wiki/Wikidata:Sandbox).

**Comment by tomayac** [comment]
Realistically won't happen for time constraints :-/ Closing.
