### ISSUE TITLE
Adds support of multi snaks sources

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#34]
Sources with n snaks should be displayed and save as such and not as n sources with single statements

**Comment by wastl** [comment]
I would say the backend already supports this, so it is only a visualisation issue. Maybe we should have issue components to make it more clear?

**Comment by Tpt** [comment]
Yes, having components would be very nice to make these things more clear.

**Comment by Tpt** [comment]
Example for this issue: Freebase id in https://www.wikidata.org/wiki/Q6286425 should only have one source with two snaks

**Comment by wastl** [comment]
In the backend it has:

curl -i https://tools.wmflabs.org/wikidata-primary-sources/entities/Q6286425

[
	{
		"dataset" :	"",
		"format" :	"v1",
		"id" :	3074471,
		"state" :	"unapproved",
		"statement" :	"Q6286425\tP646\t\"/m/03d2lfb\"\tS248\tQ20635329\tS577\t+00000002015-02-13T00:00:00Z/11",
		"upload" :	47814385608576
	}
	
]

**Comment by wastl** [comment]
Following up to the discussion in #39, I think it is not a good idea to actually have statements with multiple sources. It is better to repeat the statement for each source instead.

**Comment by Tpt** [comment]
> I think it is not a good idea to actually have statements with multiple sources.

Strong +1 as I think we have no other way if we want to keep the quick statements syntax that doesn't allow to express that two sources snaks belongs to the same source or are two different sources.

If we do this choice I think that the backend is already ok and we only have to modify the frontend.
