### ISSUE TITLE
"stated in" and "publication date" should be added as one reference, not two

### ISSUE THREAD

**Issue by mineo** [google/primarysources#35]
On https://www.wikidata.org/wiki/Q6286425 (suggests a freebase identifier) for example each of them can be added as its own reference, but they should be one.

**Comment by Tpt** [comment]
Thank you very much for this bug report. The root cause of this issue is a bug in the frontend already reported in #34

**Comment by mineo** [comment]
Ah, so that's what snaks are. Sorry for reporting this again.

**Comment by Tpt** [comment]
No problem. It is better to have 4 issues opened for the same bug than none.
