### ISSUE TITLE
Rejecting anything doesn't work

### ISSUE THREAD

**Issue by mineo** [google/primarysources#36]
On https://www.wikidata.org/wiki/Q4975456 and other items rejecting either the freebase identifier statement or the stated in reference or the publication date reference doesn't work. According to Firefox'/Chromiums network monitor the request to https://tools.wmflabs.org/wikidata-primary-sources/statements/2660076?state=wrong&user=Mineo succeeds, then the page reloads and everything's there again. None of the data disappears from https://tools.wmflabs.org/wikidata-primary-sources/entities/Q4975456 either.

**Comment by wastl** [comment]
Are you sure?

curl -i   https://tools.wmflabs.org/wikidata-primary-sources/entities/Q4975456

gives me a 404, so the entity no longer exists. It may be a caching issue, I'll check the caching code just in case.

**Comment by wastl** [comment]
I am pretty sure we can exclude a server side cache issue. Could it be a browser cache issue? In this case we'd probably want to set an Expiry time or Pragma: no-cache header.

**Comment by mineo** [comment]
Here's a screenshot showing the same thing on https://www.wikidata.org/wiki/Q7430618. The data is sent again after the POST request to https://tools.wmflabs.org/wikidata-primary-sources/statements/2934626?state=wrong&user=Mineo (at the top of the list of requests). Requesting (locally with curl, Firefox and Chromium and via curl from a different machine)
* https://tools.wmflabs.org/wikidata-primary-sources/entities/Q7430618?dataset=freebase returns an unapproved statement
* https://tools.wmflabs.org/wikidata-primary-sources/entities/Q7430618 correctly returns a 404
* but https://tools.wmflabs.org/wikidata-primary-sources/entities/Q4975456?dataset=freebase does now only return a 404 as well.

If it's any help in locating the point at which something goes wrong, although the data gets shown again, my activities counter on https://tools.wmflabs.org/wikidata-primary-sources/status.html still increases :P

![bla](https://cloud.githubusercontent.com/assets/78236/8487296/66807a9a-210b-11e5-9793-fd887f583f8f.jpg)

**Comment by wastl** [comment]
Ok, I see the bug. With the introduction of datasets at the frontend level, caching is now wrong.

**Comment by mineo** [comment]
The fix to this might have caused (or at least be related to) #39.

**Comment by wastl** [comment]
It should not, but I'll have a look again. The last change only flushes the cache and forces a reload of all statements for an entity from the persistent database when a statement of this entity has been updated.
