### ISSUE TITLE
Suggestion link does not work in IE

### ISSUE THREAD

**Issue by vrandezo** [google/primarysources#4]
The link to a random item with Freebase data does not seem to work on IE 11 on Windows 8.1 

Reported here:
https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool#Problem_with_IE.3F

**Comment by tomayac** [comment]
Sorry, I could only check this in Windows 10 (Technical Preview) and MSIE 11 and it worked. If this is still a problem, please reopen.
