### ISSUE TITLE
Approving a source of a new statement makes one of the other sources disappear

### ISSUE THREAD

**Issue by mineo** [google/primarysources#40]
This is with the freebase dataset selected and after force reloading everything in both browsers (firefox and chromium)

![bla](https://cloud.githubusercontent.com/assets/78236/8534316/838c234a-243b-11e5-84e0-190033d5e903.jpg)
![bla-after](https://cloud.githubusercontent.com/assets/78236/8534317/845110f6-243b-11e5-93b5-f4998dbc2390.jpg)
![foo](https://cloud.githubusercontent.com/assets/78236/8534319/8575565e-243b-11e5-89f1-2749c5cc1b5c.jpg)
![foo-after](https://cloud.githubusercontent.com/assets/78236/8534320/86bec662-243b-11e5-90d1-7bd36a140fde.jpg)

**Comment by Tpt** [comment]
Thank you very much for the bug report. I've deployed a change that should fix this issue.
