### ISSUE TITLE
Failed "reject" backend calls don't stop the loader animation

### ISSUE THREAD

**Issue by mineo** [google/primarysources#44]
Posting to https://tools.wmflabs.org/wikidata-primary-sources/statements/594784?state=wrong&user=Mineo (it's the genre -> folk music -> last.fm source on https://www.wikidata.org/wiki/Q337533) results in an Internal Server Error at the moment. After the request is completed, the loader animation on the "reject source" button doesn't stop.

**Comment by tomayac** [comment]
Proper exception handling for write operations is needed. The current assumption is that Wikipedia API requests always succeed.

**Comment by tomayac** [comment]
Closing, and leaving https://github.com/google/primarysources/issues/107 open instead.
