### ISSUE TITLE
Rejecting a source causes internal server errors

### ISSUE THREAD

**Issue by mineo** [google/primarysources#45]
This is with the "all sources" dataset.

![ise](https://cloud.githubusercontent.com/assets/78236/8592418/7148355c-262f-11e5-98fb-c81b62a54dcb.jpg)

**Comment by Tpt** [comment]
I believe it is related to issue #43  . The perfomance issues of the backend cause query failures

**Comment by Tpt** [comment]
The backend now uses MySQL. This issue should be solved now but feel free to reopen it if it is not the case.
