### ISSUE TITLE
Created by hand statements are sometimes not displayed

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#47]
When you create a new statement for a property whose as also some suggested statement, the newly created statement is not displayed until we reload the page.

Reported here: https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool#I_add_new_statements_and_it_is_incorrectly_attributed_to_the_Primary_sources_tool

**Comment by Daniele** [comment]
This often happens to me as well. Discussion archived here: https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool/Archive/2015#I_add_new_statements_and_it_is_incorrectly_attributed_to_the_Primary_sources_tool

**Comment by tomayac** [comment]
This seems to be working now (albeit saving took a very long time) and is not related to the Primary Sources Tool. I tested the exact case described by @Tpt (see this [diff via Primary Sources Tool](https://www.wikidata.org/w/index.php?title=Q1037207&oldid=307115994) vs. this other [diff via manual addition](https://www.wikidata.org/w/index.php?title=Q1037207&oldid=307115117). Both the *display* and the *attribution* behavior were correct. Closing for now.
