### ISSUE TITLE
Edits with the frontend should be tagged

### ISSUE THREAD

**Issue by vrandezo** [google/primarysources#5]
Edits with the frontend should be tagged, e.g. as primary-sources-frontend, as, e.g. Widar does.
Then all edits done with the tool can be easily tracked in Wikidata.
See: 
https://www.wikidata.org/wiki/Special:Tags
https://www.wikidata.org/w/index.php?title=Special:RecentChanges&tagfilter=mobile+edit

See https://www.mediawiki.org/wiki/Manual:Tags for documentation on Tags.

As per https://www.wikidata.org/wiki/Wikidata_talk:Primary_sources_tool#Taged.3F

**Comment by lydiapintscher** [comment]
:+1:

**Comment by ricordisamoa** [comment]
There's no way to attach change tags to edits made via the JavaScript frontend ([phab:T20670](//phabricator.wikimedia.org/T20670)).
WiDaR uses OAuth which automatically tags all of its edits.

**Comment by tomayac** [comment]
Would it make sense to add a statement à la "imported from" "Freebase" automatically?

**Comment by vrandezo** [comment]
Could we add a comment as tomayac suggest, and then have a tag be triggered based on a filter for this comment?

**Comment by ricordisamoa** [comment]
Any edit summary, no matter how unique, could be manually sent via the API to fraudulently simulate an action by freebase2wikidata.

**Comment by vrandezo** [comment]
I think it is OK enough to have possible impostors for the tool, but at least we would still capture all edits by the tool itself (i.e. due to fraud we might get a lowered accuracy, but coverage remains complete).

**Comment by ricordisamoa** [comment]
@tomayac @vrandezo Wait, wait! As per [T20670](//phabricator.wikimedia.org/T20670), we have free tagging now!
It is not in wbeditentity yet, though...

**Comment by lydiapintscher** [comment]
@ricordisamoa Can you open a ticket on Phabricator detailing what needs to be done for Wikibase to make this happen?

**Comment by ricordisamoa** [comment]
@lydiapintscher Hehe... if I had known what needs to be done, I would have done it.
But I think @atlight can help.

**Comment by lydiapintscher** [comment]
Thanks :)

**Comment by atlight** [comment]
Hello! If you would like to implement adding change tags via the Wikibase repository API, you might like to look at https://gerrit.wikimedia.org/r/#/c/188543/ (particularly the changes to `ApiEditPage` regarding the API logic), and https://gerrit.wikimedia.org/r/#/c/214388/1/includes/EditPage.php shows a nice way of actually adding the tags when the time comes.

If I can be of help, please let me know.
