### ISSUE TITLE
"Invalid revision ID" on every redirect

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#52]
See https://phabricator.wikimedia.org/T107080

**Comment by sjoerddebruin** [comment]
Also happening on talk pages. Isn't better to only include the item namespace and exclude all the other namespaces?

**Comment by Tpt** [comment]
Should be fixed now: https://github.com/google/primarysources/commit/07534e165dde70ad44e25dd7c8c69bb98856fb6e
