### ISSUE TITLE
Reference URLs are not display

### ISSUE THREAD

**Issue by petrux** [google/primarysources#55]
In some blue boxes reference URLs are not shown, even if the anchor text says `1 reference`. 
Please, check the [following page](https://www.wikidata.org/wiki/Q67964) at the `Bologna F.C. 1909` voice.  As a counter example, please, check the `occupation -> association football player` box, where the three URLs are correctly shown.

**Comment by marfox** [comment]
This issue is a blocker, preventing users from clicking on the reference URL.

**Comment by marfox** [comment]
@Tpt, this is actually fixed in the active deployment, but GitHub will not close it unless you merge your commit to `master`.

**Comment by Tpt** [comment]
@marfox As I am no more at Google I have lost my commit access to this repo. So, I can't do this operation.

**Comment by marfox** [comment]
Thanks for the update, @Tpt. This conversation is useful to keep track then.

**Comment by tomayac** [comment]
This seems to be working fine now. Closing.
