### ISSUE TITLE
Rejected property does not disappear.

### ISSUE THREAD

**Issue by pkmarmor** [google/primarysources#6]
When I rejected a property entirely, I expected it would disappear, but it is presented again.(Chrome, PC, Windows 7)

**Comment by wastl** [comment]
Can you give us the entity with the rejected property?

**Comment by pkmarmor** [comment]
Q3777140, rejecting suggestions for "place of birth" (all less granular than what we already have).

**Comment by pkmarmor** [comment]
Same behavior today on Q474788, Chrome on iPad, property country of citizenship.

**Comment by tomayac** [comment]
This seems to be fixed by now. I rejected the property and it didn't show up again. Please reopen should this still be an issue.

**Comment by pkmarmor** [comment]
Thanks!
