### ISSUE TITLE
Record user and datetime for all votes

### ISSUE THREAD

**Issue by tfmorris** [google/primarysources#62]
Currently when a suggestion is approved or rejected, the only thing recorded is the new state.  It would be very valuable to be able to track votes by user when doing analysis of how reliable voters are.  Date and time allows correlation with the actual edit made as well as time analysis of votes.

**Comment by Tpt** [comment]
We are already storing these data in the database in order to produce some statistics displayed at https://tools.wmflabs.org/wikidata-primary-sources/status.html and https://tools.wmflabs.org/wikidata-primary-sources/dashboard.html

We should maybe provide an API for them.

**Comment by wastl** [comment]
Indeed. The data is all there - I was just waiting for good requirements on what kind of data people would be interested in to surface. Any suggestions?

**Comment by tfmorris** [comment]
Oh, cool.  The typical RESTful/JSONy thing to do is marshall up whatever data you have that you're not filtering for security or other reasons.

Specifically, I think that statements where state!=unapproved should be returned in the API with the user and datetime the statement was processed.

**Comment by wastl** [comment]
Ok, let's see if I can easily add this tomorrow. I was originally only thinking of what kind of statistics you'd like to generate, but adding this information to the JSON serialization makes sense.

There's no real privacy issue here, we only store user name, statement id, timestamp and new state in the activity log.

**Comment by wastl** [comment]
When you retrieving statements that have been updated, you now have a list of activities (usually only one, but can be more) wrt this statement. Try it with:

curl -i "https://tools.wmflabs.org/wikidata-primary-sources/statements/any?state=wrong"

To get 10 random wrong statements. ;-)
