### ISSUE TITLE
Primary Sources statement list do not refresh after approve or reject

### ISSUE THREAD

**Issue by Crazy1880** [google/primarysources#64]
In the "Primary Sources statement list" happened to me no update or refresh. If I click approve or reject, comes the loading bar, but nothing happens. In the object it is assumed.

User Hjfocs wrote: I managed to reproduce the issue. Not only nothing happens, but it also seems that the data in the list is not in sync with the primary sources backend. @Tpt has led the tool development so far, maybe he has more insights.

**Comment by marfox** [comment]
The lack of sync between that list and the backend may be the subject of a new issue. Just opened it, #65

**Comment by addshore** [comment]
Should be closed, duplicate of https://github.com/google/primarysources/issues/58
