### ISSUE TITLE
Statement list is not in sync with the backend

### ISSUE THREAD

**Issue by marfox** [google/primarysources#65]
The data in the list doesn't seem to be in sync with the backend.

**Comment by wastl** [comment]
Can you give some more details? Is the statement list available in the backend when accessing with curl? If the same problem happens with curl, it is likely a caching issue (I'll check).

**Comment by marfox** [comment]
Hi @wastl, see for instance [Q354529](https://www.wikidata.org/wiki/Q354529), dataset `FBK-strephit-soccer`.
Statement list:
![statement-list](https://cloud.githubusercontent.com/assets/4838312/10277970/1e7ba4ec-6b5a-11e5-9760-70fa7a22df18.png)
Front end:
![front-end](https://cloud.githubusercontent.com/assets/4838312/10277971/1e7d32da-6b5a-11e5-8ced-f202f6593da4.png)
API call:
https://tools.wmflabs.org/wikidata-primary-sources/entities/Q354529?dataset=FBK-strephit-soccer&state=approved
```json
{"activities":[{"state":"approved","timestamp":"+2015-09-08T18:15:28Z/14","user":"CristianCantoro"}],"dataset":"","format":"v1","id":19594295,"state":"approved","statement":"Q354529\tP54\tQ6767\tS854\t\"http://www.treccani.it/enciclopedia/massimiliano-allegri/\"","upload":48974752},
...
{"activities":[{"state":"approved","timestamp":"+2015-09-10T12:16:44Z/14","user":"Aubrey"}],"dataset":"","format":"v1","id":18385145,"state":"approved","statement":"Q354529\tP54\tQ6767\tS854\t\"http://biografieonline.it/biografia.htm?BioID=2404&biografia=Massimiliano+Allegri\"","upload":48974752}
```

**Comment by tomayac** [comment]
This can be closed for the same reason as https://github.com/google/primarysources/issues/71: the source ```biografieonline.it``` was (on purpose or not, separate off-issue discussion started by @marfox) blacklisted.
