### ISSUE TITLE
Don't credit user for blacklisted & duplicates

### ISSUE THREAD

**Issue by tfmorris** [google/primarysources#67]
From looking at the front end script:

https://github.com/google/primarysources/blob/master/frontend/freebase2wikidata.js#L1479
https://github.com/google/primarysources/blob/master/frontend/freebase2wikidata.js#L689

it appears that marking statements as duplicates or blacklisted are credited to the current user even though they're entirely automatic processes without any user input.  This doesn't make any sense to me, particularly if this also gets rolled up for the top users stats.

**Comment by tomayac** [comment]
Hi @tfmorris,

Sorry for the long turn-around time.

From what I see, no harm is done attributing automated state changes to the current user, but I agree that these automated changes should not be reflected in the (gamification) [stats](https://tools.wmflabs.org/wikidata-primary-sources/status.html). @wastl, can you modify the leaderboard so that it only considers manual changes in the "Top Users" section?

**Comment by tfmorris** [comment]
Filtering after the fact would be better than nothing, but the reason that I prefer they not be recorded as user events is that: a) the user took no action, the software did, so they shouldn't be blamed or credited and b) relying on post-hoc filtering is more error prone and doesn't meet the [Principle of Least Surprise](https://en.wikipedia.org/w/index.php?title=Principle_of_least_surprise)

**Comment by wastl** [comment]
I changed that behaviour (both the actual logging and the presentation in the status dashboard), though I don't see how this really is an issue. I'd argue the Principle of Least Surprise here would be that every state change reported to the backend should be logged as user activity. It is always surprising to have exceptions.

There is no "attribution" built into the system. It merely contains an event log listing what actions where triggered, mostly for debugging purposes. 

Filtering is trivial, just ignore everything that has state DUPLICATE or BLACKLISTED.

**Comment by tfmorris** [comment]
Thanks!
