### ISSUE TITLE
No value qualifiers not handled properly (causes TypeErrors)

### ISSUE THREAD

**Issue by mariushoch** [google/primarysources#69]
The primary sources tool doesn't properly handle no value qualifiers, as it assumes all qualifiers to have a data value at https://github.com/google/primarysources/blob/8bdb7f995a923390400814e02b2f88cf1f7b1834/frontend/freebase2wikidata.js#L1031

Causes `TypeError: undefined is not an object (evaluating 'dataValue.type')` on for example https://www.wikidata.org/wiki/Q5593

**Comment by tomayac** [comment]
The actual source of the error is located. herehttps://github.com/google/primarysources/blob/8bdb7f995a923390400814e02b2f88cf1f7b1834/frontend/freebase2wikidata.js#L1043. Needs further investigation.
