### ISSUE TITLE
Bad formatting of time values

### ISSUE THREAD

**Issue by marfox** [google/primarysources#83]
The front-end currently displays all time values like this:
`+1998-0-0T0:0:0Z/`
It used to work before.
May be related to #41

**Comment by marfox** [comment]
The back-end also seems to manipulate the original QuickStatements, and adds weird unicode characters.
For instance, original QuickStatement:
`Q352361	P570	+00000001875-01-01T00:00:00Z/9	S854	"http://www.uni-stuttgart.de/hi/gnt/dsi2/index.php?table_name=dsi&function=details&where_field=id&where_value=7974"`
VS uploaded:
`Q352361\tP570\t+1875-0\u0001-0\u0001T0\u0000:0\u0000:0\u0000Z/\t\tS854\t\"http://www.uni-stuttgart.de/hi/gnt/dsi2/index.php?table_name=dsi&function=details&where_field=id&where_value=7974\"`

**Comment by marfox** [comment]
The time value in the back-end DB seems fine:
```
+----------+----------+--------+--------+------+------+---------------------+-----------+------+-------+
| id       | property | svalue | dvalue | lat  | lng  | tvalue              | precision | lang | vtype |
+----------+----------+--------+--------+------+------+---------------------+-----------+------+-------+
| 40358852 | P570     | NULL   |   NULL | NULL | NULL | 1875-01-01 00:00:00 |         9 | NULL | time  |
+----------+----------+--------+--------+------+------+---------------------+-----------+------+-------+
```

**Comment by Crazy1880** [comment]
In the fronend, if you click approve, you'll became a "invalid snak". See screenshot:
![2016-03-25_invalid_snak](https://cloud.githubusercontent.com/assets/14944867/14042383/b7d310a2-f279-11e5-89ea-397cdbfe1054.JPG)

**Comment by Tpt** [comment]
I believe that the root cause of this issue is an encoding issue in Marco's file that have broken the import system: as the time value were badly formatted the import tool thought they were string and not dates.

**Comment by marfox** [comment]
@Tpt I don't think so, this affects all the datasets, also those that were imported previously

**Comment by Tpt** [comment]
Yes, you are right, my bad. So, I believe we have to investigate in the backend serialisation code

**Comment by marfox** [comment]
Maybe [here](../blob/master/backend/SerializerTSV.cc#L35)?

**Comment by Tpt** [comment]
I believe that the root cause of the issue is that https://github.com/google/primarysources/commit/c06088db6f90463c891a5f847117130f248c9059 have not updated the toWikidataString() method. I'm writing a PR to fix that

**Comment by Tpt** [comment]
I have just deployed the related change. If should work now.

**Comment by marfox** [comment]
:ok_hand: Works like a charm.

**Comment by Crazy1880** [comment]
Works, thanks
