### ISSUE TITLE
glitch when accepting a new claim

### ISSUE THREAD

**Issue by lydiapintscher** [google/primarysources#9]
I just approved "original language of work:Japanese". After the page is reloaded the same claim is suggested again.

![wikidataclientwatchlistintegration1](https://cloud.githubusercontent.com/assets/550412/6984297/aad44558-da27-11e4-91e4-c992c80a9dd5.png)

**Comment by lydiapintscher** [comment]
This happened on Q2665450 in case it makes a difference.

**Comment by tomayac** [comment]
This is due to https://twitter.com/tomayac/statuses/579822321763913728. When I change something via the JavaScript library, the API doesn't reflect the changes right away. Can you ping me offline regarding the caching policy? You have my contacts :-) Thanks!
